TorigoyaMZ_FixLoadImageMZ15:
  version: '1.0.0'
  target: 'MZ'
  title:
    ja: 'MZ v.1.5 でブラウザプレイ時に画像が表示されない不具合修正パッチ'
  body:
    ja: |
      ※このプラグインはRPGツクールMZ 1.5.0で動作確認しています。
      　今後のRPGツクールMZのアップデート次第では不要になる可能性があります。

      ■ なにこれ！
      RPGツクールMZ v.1.5コアスクリプトの不具合の修正パッチです。
      ふりーむ！やアツマール、PLiCyなどでブラウザプレイをした際に、
      画像が読み込まれないことがある不具合を修正します。

      ■ 原因
      RPGツクールMZ 1.4.3 → 1.5.0 の変更に画像読み込み処理の変更が原因です。
      （Bitmap.prototype._startLoading の処理）

      この中で画像の読み込み開始時に、もしも画像に既に width （幅）が存在していれば、
      画像は既に読み込まれているものと判断して、
      読み込み完了後の処理を直ちに実行するような形に変更されています。

      ですが、実際には画像の width （幅）が存在しているからといって、
      この時点で画像が描画に利用できるとは限りません。
      正しくはブラウザの画像読み込み処理の完了通知を待つ必要があります。

      この修正パッチプラグインでは、該当の処理を v.1.4.3 コアスクリプトの同等のものに戻し、
      きちんとブラウザが画像を読み込むのを待ってから処理を実行するようにします。
  parameter: []
