base: &base
  version: '2.1.0'
  title:
    ja: 'セーブコマンド追加プラグイン（オートセーブ）'
  parameter: {}

TorigoyaMZ_SaveCommand2:
  <<: *base
  target: 'MZ'
  body:
    ja: |
      イベントコマンドの「プラグインコマンド」を使って、
      イベント中に自動的にセーブを実行できるようになります。
  commands:
    saveWithId:
      name: '【セーブ】スロットIDを指定してセーブ'
      desc: |
        指定のスロットIDにセーブを実行します。
        0は「オートセーブ」用スロットです。
      parameter:
        slotId:
          type: 'integer'
          name: 'スロットID'
          desc: |
            セーブするスロットのID
          min: 0
          default: 1
        skipUpdateTimestamp:
          type: 'boolean'
          name: 'セーブ日時の更新をスキップ'
          desc: |
            ロード時のカーソル位置移動防止のため
            セーブ日時の更新処理をスキップします
          on: 'スキップする'
          off: 'スキップしない（標準）'
          default: 'false'
    saveWithVariable:
      name: '【セーブ】変数でスロットIDを指定してセーブ'
      desc: |
        指定した変数の値のスロットIDにセーブを実行します
      parameter:
        slotVariableId:
          type: 'variable'
          name: 'スロットIDが入った変数'
          desc: |
            セーブするスロットのIDを指定する変数
        skipUpdateTimestamp:
          type: 'boolean'
          name: 'セーブ日時の更新をスキップ'
          desc: |
            ロード時のカーソル位置移動防止のため
            セーブ日時の更新処理をスキップします
          on: 'スキップする'
          off: 'スキップしない（標準）'
          default: 'false'
    saveLastSlot:
      name: '【セーブ】最後にセーブしたスロットに上書き'
      desc: |
        最後にセーブしたスロットに上書きセーブします
      parameter:
        skipUpdateTimestamp:
          type: 'boolean'
          name: 'セーブ日時の更新をスキップ'
          desc: |
            ロード時のカーソル位置移動防止のため
            セーブ日時の更新処理をスキップします
          on: 'スキップする'
          off: 'スキップしない（標準）'
          default: 'false'
    deleteWithId:
      name: '【削除】スロットIDを指定してセーブ削除'
      desc: |
        【！取り扱い注意！】
        指定のスロットIDのセーブデータを削除します
      parameter:
        slotId:
          type: 'integer'
          name: 'スロットID'
          desc: |
            セーブを削除するスロットのID
          min: 0
          default: 1
    deleteWithVariable:
      name: '【削除】変数でスロットIDを指定してセーブ削除'
      desc: |
        【！取り扱い注意！】
        指定した変数の値のスロットIDのセーブデータを削除します
      parameter:
        slotVariableId:
          type: 'variable'
          name: 'スロットIDが入った変数'
          desc: |
            セーブを削除するスロットのIDを指定する変数
    deleteLastSlot:
      name: '【削除】最後にセーブしたスロットを削除'
      desc: |
        【！取り扱い注意！】
        最後にセーブしたスロットのセーブデータを削除します
