base: &base
  version: '1.1.0'
  title:
    ja: '装備画面で武器は外せないようにするプラグイン'
  body:
    ja: |
      武器を付け替えはできても、武器無しにはできないようにします。

      ------------------------------------------------------------
      ■ 上級者向け：武器以外も外せないようにする
      ------------------------------------------------------------
      プラグイン設定で「装備タイプ」のIDを指定することで、
      武器以外の装備品も外せないようにできます。
      設定は複数追加することができます。

  parameter:
    advanced:
      dummy: '■ 上級設定'
    advancedSlotIds:
      parent: 'advanced'
      name: '装備を外せなくする装備タイプID'
      type: 'integer'
      array: true
      desc: |
        装備を外せなくする「装備タイプ」のIDを指定します。
      default: [1]

Torigoya_NotRemoveWeapon:
  <<: *base
  target: 'MV'

TorigoyaMZ_NotRemoveWeapon:
  <<: *base
  target: 'MZ'
