base: &base
  version: '1.1.1'
  title:
    ja: '使用後にステート追加スキルプラグイン'
  body:
    ja: |
      スキル使用時に使用者にステートを追加/削除できるようにします。
      「相手に大ダメージを与えるが、自分は毒になる」のようなスキルが作れます。

      ------------------------------------------------------------
      ■ 設定方法
      ------------------------------------------------------------
      スキルのメモ欄に以下のように記述してください。

      ■ 例1：使用者に10番のステートを付与する

      <AddState: 10>

      または

      <ステート追加: 10>

      ■ 例2：使用者に10番と11番のステートを付与する（「,」区切りで指定）

      <AddState: 10, 11>

      または

      <ステート追加: 10, 11>

      ■ 例3：使用者に10番のステートを削除する

      <RemoveState: 10>

      または

      <ステート削除: 10>

      ■ 例4：使用者のパーティ全員に10番のステートを付与する

      <AddStateUnit: 10>

      または

      <ステート追加全体: 10>

  parameter: {}

Torigoya_AddStateSkill:
  <<: *base
  target: 'MV'

TorigoyaMZ_AddStateSkill:
  <<: *base
  target: 'MZ'
