base: &base
  version: '1.1.0'
  title:
    ja: 'メニューからコモンイベント呼び出しプラグイン'
  body:
    ja: |
      メニューにコモンイベントを呼び出す項目を追加します

      ------------------------------------------------------------
      ■ 設定方法
      ------------------------------------------------------------

      このプラグインの設定からメニュー項目を登録してください。
      ここでの並び順の順番で画面に表示されます。

parameterBase: &parameterBase
  base:
    dummy: '■ 基本設定'
  baseItems:
    parent: 'base'
    name: 'メニューに追加する項目'
    type: 'MenuItem'
    array: true
    default:
      - '{"name": "コモンイベント","commonEvent": "1","switchId": "0","visibility": "true","note": ""}'

structureBase: &structureBase
  MenuItem:
    name:
      name: '項目名'
      type: 'string'
      desc: |
        メニューに表示される項目の名前
      default: ''
    commonEvent:
      name: '呼び出すコモンイベント'
      type: 'common_event'
      desc: |
        メニュー選択時に呼び出すコモンイベント
      default: 0
    switchId:
      name: '有効スイッチ'
      desc: |
        このスイッチがONのときのみ選択できるようにします
        なしの場合は、常に選択できます
      type: 'switch'
      default: 0
    visibility:
      name: '無効時に表示するか'
      desc: |
        有効スイッチがONじゃないときに
        項目をメニューに表示するか設定できます
      type: 'boolean'
      on: '表示する'
      off: '表示しない'
      default: 'true'
    note:
      name: 'メモ'
      desc: |
        メモ欄です。
        ツクールのメモ欄同様に使えます。
      type: 'multiline_string'
      default: ''

Torigoya_CommonMenu:
  <<: *base
  target: 'MV'
  parameter:
    <<: *parameterBase
  structures:
    <<: *structureBase

TorigoyaMZ_CommonMenu:
  <<: *base
  target: 'MZ'
  parameter:
    <<: *parameterBase
  structures:
    <<: *structureBase
