TorigoyaMZ_ActorEnemy:
  version: '0.1.0'
  target: 'MZ'
  title:
    ja: 'アクター使用エネミープラグイン'
  body:
    ja: |
      ※注意：このプラグインは性質上あらゆるプラグインと競合しやすいです
      アクターを敵として出現させます。
      サイドビューバトルでの使用を想定しています。

      ------------------------------------------------------------
      ■ 設定方法
      ------------------------------------------------------------
      以下の2つをデータベースで設定する必要があります。

      ・敵として出現させたい「アクター」
      ・敵自体の設定をするための「敵キャラ」

      敵キャラのメモ欄には以下のように記述してください。

      ■ 例：10番のアクターを敵キャラとして出現させる
      <useActor: 10>

      または

      <アクターID: 10>
  parameter:
    base:
      dummy: '■ 基本設定'
    callRecoverAll:
      parent: 'base'
      name: '戦闘開始前に敵アクターのHP/MPなどを回復するか？'
      type: 'boolean'
      on: '回復する'
      off: '回復しない'
      desc: |
        戦闘開始時に自動的に敵アクターを全回復するか設定します。
        HP残量などもイベントで操作したい場合はOFFにしてください。
      default: true
