soundConfig: &soundConfig
  name:
    name: '効果音ファイル名'
    desc: |
      通知表示時に再生する効果音ファイル
      空っぽの場合は効果音なしになります
    type: 'file'
    dir: 'audio/se/'
    default: ''
  volume:
    name: '効果音の音量'
    desc: |
      通知表示時に再生する効果音の音量（%）
    type: 'number'
    min: 0
    max: 100
    default: 90
  pitch:
    name: '効果音のピッチ'
    desc: |
      通知表示時に再生する効果音のピッチ（%）
    type: 'number'
    min: 0
    max: 200
    default: 100
  pan:
    name: '効果音の位相'
    desc: |
      通知表示時に再生する効果音の位相
    type: 'number'
    min: -100
    max: 100
    default: 0

TorigoyaMZ_NotifyMessage:
  version: '1.3.0'
  title:
    ja: '通知メッセージプラグイン'
  target: 'MZ'
  body:
    ja: |
      画面の左下から通知メッセージを表示する機能を追加します。
      通知メッセージはプラグインコマンドで表示できます。

      ------------------------------------------------------------
      ■ メモ欄を使ったカスタマイズ
      ------------------------------------------------------------
      プラグインコマンドのメモ欄に以下の記述を行うことで
      通知ごとに一部動作をカスタマイズすることができます。

      ▼ 表示時の効果音を無しにする
      <noSound>
  base:
    - 'TorigoyaMZ_FrameTween'
  orderAfter:
    - 'TorigoyaMZ_FrameTween'
  parameter:
    base:
      dummy: '■ 基本設定'
    baseAppearTime:
      parent: 'base'
      name: '登場/退場時間'
      type: 'integer'
      desc: |
        通知が画面にスクロールイン/アウトする時間（フレーム数/60＝1秒）を指定します。
      min: 0
      default: 15
    baseViewTime:
      parent: 'base'
      name: '表示時間'
      type: 'integer'
      desc: |
        通知の表示時間（フレーム数/60＝1秒）を指定します。0にすると画面外に押し出されるまで消えなくなります。
      min: 0
      default: 90
    baseFontSize:
      parent: 'base'
      name: '文字サイズ'
      type: 'integer'
      min: 1
      desc: |
        通知メッセージの文字サイズを指定します
      default: 22
    basePadding:
      parent: 'base'
      name: '余白サイズ'
      type: 'integer'
      min: 0
      desc: |
        通知メッセージの全体的な余白サイズを指定します
      default: 4
    baseLeftPadding:
      parent: 'base'
      name: '左側の追加余白サイズ'
      type: 'integer'
      min: 0
      desc: |
        通知メッセージの左側の余白サイズを指定します。
        全体の余白サイズに加え、この分が余白に追加されます。
      default: 0
    baseRightPadding:
      parent: 'base'
      name: '右側の追加余白サイズ'
      type: 'integer'
      min: 0
      desc: |
        通知メッセージの右側の余白サイズを指定します。
        全体の余白サイズに加え、この分が余白に追加されます。
      default: 30
    baseItemPadding:
      parent: 'base'
      name: 'アイコンと文章の余白'
      type: 'integer'
      min: 0
      desc: |
        通知アイコンとメッセージの間の余白サイズを指定します
      default: 5
    baseSound:
      parent: 'base'
      name: '効果音'
      type: Sound
      desc: |
        通知表示時の効果音を指定します。
      default: '{"name":"Item1","volume":"90","pitch":"100","pan":"0"}'
    advanced:
      dummy: '■ 上級設定'
    advancedVisibleSwitch:
      parent: 'advanced'
      name: '有効スイッチ'
      type: 'switch'
      desc: |
        このスイッチがONのときのみ画面に通知を表示するようにします。「なし」の場合は常に表示されます。
      default: 0
    advancedBackgroundColor1:
      parent: 'advanced'
      name: '背景グラデーション:左端'
      type: 'string'
      desc: |
        背景グラデーションの左端の色を指定します。
        色はCSSの記法で指定できます。
      default: 'rgba(0, 0, 64, 0.6)'
    advancedBackgroundColor2:
      parent: 'advanced'
      name: '背景グラデーション:右端'
      type: 'string'
      desc: |
        背景グラデーションの右端の色を指定します。
        色はCSSの記法で指定できます。
      default: 'rgba(0, 32, 64, 0)'
    advancedUiPaddingBottom:
      parent: 'advanced'
      name: 'UIエリア余白: 下端'
      desc: |
        通知メッセージ表示位置の下側の余白を指定します。
      type: 'integer'
      default: 5
    advancedKeepMessage:
      parent: 'advanced'
      name: 'シーン遷移しても表示をキープ'
      desc: |
        【危険：環境によってはONにすると不具合の原因となります】シーン遷移してもメッセージを全消ししないようにします。
      type: 'boolean'
      on: 'キープする（危険）'
      off: 'キープしない（安全）'
      default: false

  structures:
    Sound:
      <<: *soundConfig

  commands:
    notify:
      name: '通知の表示'
      desc: '指定内容の通知を表示します'
      parameter:
        message:
          type: 'multiline_string'
          name: 'メッセージ'
          desc: |
            通知に表示する文章を指定します。「文章の表示」のコマンドが一部利用できます。
        icon:
          type: 'number'
          name: 'アイコンID'
          desc: |
            通知に表示するアイコンのIDを指定します。
            0の場合は表示しません。
        note:
          type: 'note'
          name: 'メモ欄'
          desc: |
            メモ欄です。
            ツクールのメモ欄と同様に利用できます。
    notifyWithVariableIcon:
      name: '通知の表示(アイコン変数指定)'
      desc: '指定内容の通知を表示します。アイコンのIDを変数で指定します。'
      parameter:
        message:
          type: 'multiline_string'
          name: 'メッセージ'
          desc: |
            通知に表示する文章を指定します。「文章の表示」のコマンドが一部利用できます。
        iconVariable:
          type: 'variable'
          name: 'アイコンID（変数指定）'
          desc: |
            通知に表示するアイコンIDが設定された変数を指定します。
            変数の中身が0またはマイナスの場合は表示しません。
        note:
          type: 'note'
          name: 'メモ欄'
          desc: |
            メモ欄です。
            ツクールのメモ欄と同様に利用できます。

TorigoyaMZ_NotifyMessage_AddonGetItem:
  version: '1.2.0'
  title:
    ja: '通知メッセージアドオン: アイテム獲得表示'
  target: 'MZ'
  body:
    ja: |
      以下のイベントコマンド実行時に自動的に通知メッセージを表示します。
      ※増やす場合のみ表示されます

      ・所持金の増減
      ・アイテムの増減
      ・武器の増減
      ・防具の増減

      ------------------------------------------------------------
      ■ 表示したくない場合
      ------------------------------------------------------------
      例えばお金の入手メッセージはいらない！という場合は、
      お金の入手メッセージの内容を空欄にしてください。
  base:
    - 'TorigoyaMZ_NotifyMessage'
  orderAfter:
    - 'TorigoyaMZ_NotifyMessage'
  parameter:
    base:
      dummy: '■ 基本設定'
    baseGainSingleMessage:
      parent: 'base'
      name: 'アイテム入手メッセージ（1つ）'
      type: 'string'
      desc: |
        アイテムを1つ入手したときのメッセージを設定します。（\name : アイテム名）
      default: '\c[2]\name\c[0] を手に入れた！'
    baseGainMultiMessage:
      parent: 'base'
      name: 'アイテム入手メッセージ（複数）'
      type: 'string'
      desc: |
        アイテムを複数入手したときのメッセージを設定します。（\name : アイテム名  \count : 個数）
      default: '\c[2]\name\c[0] ×\count を手に入れた！'
    baseGainMoneyMessage:
      parent: 'base'
      name: 'お金入手メッセージ'
      type: 'string'
      desc: |
        お金を入手したときのメッセージを設定します。（\gold : 獲得金額）
      default: '\gold\c[4]\G\c[0] を手に入れた！'
    baseGainMoneyIcon:
      parent: 'base'
      name: 'お金入手アイコン'
      type: 'number'
      desc: |
        お金を入手したときのアイコンIDを設定します。0の場合はアイコンを表示しません。
      default: 0
    advanced:
      dummy: '■ 上級設定'
    advancedSwitch:
      parent: 'advanced'
      name: '有効スイッチ'
      type: 'switch'
      desc: |
        このスイッチがONのときのみ画面に通知するようにします。「なし」の場合は常に通知されます。
      default: 0
    advancedGainItemSound:
      parent: 'advanced'
      name: 'アイテム入手効果音の上書き'
      type: 'CustomSound'
      desc: |
        アイテムを入手したときに再生する効果音を指定します。
        上書き設定をしない場合は通常の通知音が再生されます。
      default: '{"overwrite":"false","sound":"{\"name\":\"\",\"volume\":\"90\",\"pitch\":\"100\",\"pan\":\"0\"}"}'
    advancedGainMoneySound:
      parent: 'advanced'
      name: 'お金入手効果音の上書き'
      type: 'CustomSound'
      desc: |
        お金を入手したときに再生する効果音を指定します。
        上書き設定をしない場合は通常の通知音が再生されます。
      default: '{"overwrite":"false","sound":"{\"name\":\"\",\"volume\":\"90\",\"pitch\":\"100\",\"pan\":\"0\"}"}'
  structures:
    CustomSound:
      overwrite:
        name: '効果音設定の上書き'
        desc: |
          通知表示時に再生する効果音を
          デフォルトから上書き設定するか指定します。
        type: 'boolean'
        on: '上書きする'
        off: '上書きしない'
        default: false
      sound:
        name: '効果音'
        desc: |
          上書き設定する効果音の内容を指定します。
          上書きしない場合、この設定は無視されます。
        type: 'Sound'
        default: '{"name":"","volume":"90"}'
    Sound:
      <<: *soundConfig

TorigoyaMZ_NotifyMessage_AddonAtsumaruGlobalSignal:
  version: '1.0.2'
  title:
    ja: '通知メッセージアドオン: アツマールグローバルシグナル通知ログ'
  target: 'MZ'
  body:
    ja: |
      ※このプラグインはゲームアツマール用の非公式プラグインです

      ゲームアツマールのグローバルシグナルAPIを利用して
      全ユーザーで共有のイベントログを表示する機能を追加します。

      ------------------------------------------------------------
      ■ 注意事項
      ------------------------------------------------------------
      ・非公式のプラグインです。突然動かなくなる場合があります。

      ・イベントログのデータサイズが大きい場合、
      　APIのサイズ上限に引っかかり正常に送信できない場合があります

      ・他のプラグインからグローバルシグナルAPIを使用している場合
      　競合する可能性があります。ご注意ください。

      ------------------------------------------------------------
      ■ 使用方法：イベントログの設定
      ------------------------------------------------------------
      事前に表示するイベントログの種類を登録する必要があります。

      「イベントログ種別」に以下の情報を設定してください。

      ・種別キー
      イベントログの種類を表す言葉です。
      ここで設定した言葉をイベントコマンドで使用します。
      データサイズが小さい、短い英語がおすすめ！

      ・ログ文章
      イベントログの文章として表示するテンプレートを設定します。
      ここで設定した文章が通知として表示されます。
      ここには一部特殊な記法を利用することができます（後述）

      ・アイコンID
      通知に表示するアイコンを設定します

      ------------------------------------------------------------
      ■ 使用方法：通知の発行
      ------------------------------------------------------------
      通知を発行したいタイミングで
      プラグインコマンドの「イベントログの送信」を実行してください。

      種別キーには「イベントログ種別」で設定したものを指定してください。

      ------------------------------------------------------------
      ■ ログ文章の記法について
      ------------------------------------------------------------
      ログ文章には文章の表示と同様の記法を利用できます。

      ＜通知を送った人の名前について＞
      文章中に \SIG_NAME と記述することで、
      その通知を送った人のアツマール上での名前が表示されます。

      使用例） \SIG_NAME さんがログインしました

      ＜変数などの表示について＞
      \V[xx] などの変数表示は自分自身のものが表示されます。
      そのため、他のプレイヤーが送ったイベント通知であっても、
      他のプレイヤーの変数ではなく自分の変数が表示されてしまいます。

      もし、他のプレイヤーの変数の中身が表示されてほしい場合は、
      \V[xx] ではなく \SIG_V[xx] と指定してください。

      使用例） \SIG_NAME が \SIG_V[1] ゴールド獲得！
  base:
    - 'TorigoyaMZ_NotifyMessage'
  orderAfter:
    - 'TorigoyaMZ_NotifyMessage'
  parameter:
    base:
      dummy: '■ 基本設定'
    baseEventLogs:
      parent: 'base'
      name: 'イベントログ種別'
      type: 'EventLog'
      array: true
      desc: |
        イベントログの種類を定義します。
      default: []
    baseFirstFetchLimit:
      parent: 'base'
      name: '起動時に過去ログを最大何件取得するか？'
      type: 'integer'
      min: 0
      desc: |
        起動時に最大何件のログを取得するか指定します。
      default: 5
    advanced:
      dummy: '■ 上級設定'
    advancedForceMute:
      parent: 'advanced'
      name: '効果音を強制無効化'
      type: 'boolean'
      on: '強制無効化する'
      off: '無効化しない'
      desc: |
        通知の効果音を強制的に無効化するか選択できます。
        うるさいので無効化がオススメ。
      default: true
    advancedFetchInterval:
      parent: 'advanced'
      name: 'グローバルシグナルの取得間隔(秒)'
      type: 'integer'
      min: 10
      desc: |
        グローバルシグナルを何秒おきに取得するか設定します。
        短くしすぎるとAPI上限に引っかかるため注意。
      default: 60

  structures:
    EventLog:
      key:
        name: '種別キー'
        desc: |
          イベント種別の識別名です。
          ここで設定した文字列をログ送信時に指定します。
      message:
        type: 'multiline_string'
        name: 'ログ文章'
        desc: |
          ログとして表示するメッセージを指定します。
          一部特殊な記法があります。説明を読んでね。
      icon:
        type: 'number'
        name: 'アイコンID'
        desc: |
          通知に表示するアイコンのIDを指定します。
          0の場合は表示しません。
      note:
        type: 'note'
        name: 'メモ欄'
        desc: |
          メモ欄です。
          ツクールのメモ欄と同様に利用できます。
  commands:
    sendEvent:
      name: 'イベントログの送信'
      desc: '指定のイベントログを送信します'
      parameter:
        key:
          type: 'string'
          name: '種別キー'
          desc: |
            送信するイベント種別の識別名です。
            プラグイン設定で指定したものを指定してください。
        iconVariable:
          type: 'variable'
          name: 'アイコンID（変数指定）'
          desc: |
            通知に表示するアイコンIDが設定された変数を指定します。
            「なし」の場合はデフォルトのアイコンを使用します。
          default: 0
