base: &base
  version: '1.0.0'
  title:
    ja: 'アツマールコメント不透明度変更プラグイン'
  body:
    ja: |
      ※このプラグインはゲームアツマール用の非公式プラグインです
      ゲームアツマールに表示されるコメントの不透明度を変更します。

      ------------------------------------------------------------
      ■ Q&A
      ------------------------------------------------------------
      Q. ゲーム中に不透明度を変更できますか？
      A. プラグインコマンドで変更できます。
      　 なお、セーブデータには反映されないため、
      　 タイトル画面に戻ったりするともとに戻ります。
      　 （イベントシーン的な部分で使うことを想定しているよ）

      Q. ギフトの不透明度は変わりますか？
      A. ギフトはゲーム本体とは別のレイヤーにあるため
      　 どうやっても変更できません。

parameterBase: &parameterBase
  base:
    dummy: '■ 基本設定'
  defaultOpacity:
    parent: 'base'
    name: '不透明度'
    desc: |
      コメントの不透明度を設定します。
      0～255で設定してください。0だと完全に透明になります。
    type: 'integer'
    min: 0
    max: 255
    default: 255

Torigoya_AtsumaruCommentOpacity:
  <<: *base
  target: 'MV'
  parameter:
    <<: *parameterBase

TorigoyaMZ_AtsumaruCommentOpacity:
  <<: *base
  target: 'MZ'
  parameter:
    <<: *parameterBase
  commands:
    changeOpacity:
      name: 'コメント不透明度の変更'
      desc: |
        アツマールのコメントの不透明度を変更します。
      parameter:
        opacity:
          type: 'integer'
          name: '不透明度'
          desc: |
            コメントの不透明度を設定します。
            0～255で設定してください。0だと完全に透明になります。
    resetOpacity:
      name: 'コメント不透明度の初期化'
      desc: |
        コメントの不透明度を初期値に戻します。
