base: &base
  version: '1.0.0'
  title:
    ja: 'ターン消費なしスキルプラグイン'
  body:
    ja: |
      選択するとターンを消費せずに即発動するスキルを追加します。
      このプラグインは「ターン制」の戦闘システムでのみ動作します。

      ------------------------------------------------------------
      ■ 設定方法
      ------------------------------------------------------------
      スキルのメモ欄に以下のように記述してください。

      <QuickSkill>

      もしくは

      <ターン消費なし>

      ------------------------------------------------------------
      ■ おやくそく
      ------------------------------------------------------------
      ・ターン消費なしスキルは味方専用です。敵は使えません
      ・複雑なことをするとおかしくなる可能性があります（特にコモンイベント）

  parameter:
    advanced:
      dummy: '■ 上級者向け設定'
    reCalcActionTime:
      parent: 'advanced'
      name: '行動回数の再計算'
      desc: |
        ターン消費なしスキル後に行動回数の再計算を行う対象。
        行動回数が増えるステートを扱う場合は設定してください。
      type: 'select'
      option:
        - name: 'なし'
          value: 'none'
        - name: '使用者のみ'
          value: 'self'
        - name: 'パーティ全員'
          value: 'party'
      default: 'none'

TorigoyaMZ_QuickSkill:
  <<: *base
  target: 'MZ'
