base: &base
  version: '1.0.1'
  title:
    ja: 'スキルコスト表示拡張プラグイン'
  body:
    ja: |
      スキル一覧の消費コスト表示を拡張します。

      ・数値だけではなく「MP10」のようにラベル付きで表示できるようにします
      ・MPとTPを両方使う場合は両方表示します
      　　・ロンチプラグインの「HPConsumeSkill」のHP消費にも対応します

parameterBase: &parameterBase
  base:
    dummy: '■ 基本設定'
  labelFontSize:
    name: 'ラベルのサイズ'
    desc: |
      コスト表示部分のラベル(MPなどの部分)の文字サイズ
      0の場合はラベルを表示しません
    type: 'number'
    min: 0
    default: 14
  valueFontSize:
    name: '数値のサイズ'
    desc: |
      コスト表示部分の数値の文字サイズ
    type: 'number'
    min: 1
    default: 20
  gapSize:
    name: '隙間のサイズ'
    desc: |
      コスト表記が複数ある場合の隙間のサイズ
    type: 'number'
    min: 0
    default: 6

TorigoyaMZ_DrawSkillCost:
  <<: *base
  target: 'MZ'
  parameter:
    <<: *parameterBase
  orderAfter:
    - 'HPConsumeSkill'
