base: &base
  version: '2.0.0'
  title:
    en: '[Base] Tween-animation Engine'
    ja: '[鳥小屋.txt ベースプラグイン] Tweenアニメーション'
  body:
    en: 'This plugin is a base-plugin for Torigoya plugins.'
    ja: |
      このプラグインはベースプラグインです。
      このプラグインを導入しただけでは特に何も起きません。
      Tweenアニメーション用の処理を追加します。
  parameter: {}

Torigoya_FrameTween:
  <<: *base
  target: 'MV'
