base: &base
  version: '1.2.1'
  title:
    ja: 'ニコニ広告通知バー風表示プラグイン'
  body:
    ja: |
      ※このプラグインはRPGアツマール用の非公式プラグインです

      RPGアツマール上でゲームにニコニ広告された場合に、
      昔のニコ生っぽい広告バーを画面に表示をします。

parameterBase: &parameterBase
  test:
    dummy: '■ テストプレイ設定'
  testUseDebugMode:
    parent: 'test'
    name: 'テストモード'
    desc: |
      テストプレイ時にダミーの広告を表示するか？
      テストプレイ以外では強制的にオフになります。
    type: 'boolean'
    on: '使用する'
    off: '使用しない'
    default: false
  base:
    dummy: '■ 基本設定'
  baseTitle:
    parent: 'base'
    name: 'タイトル'
    desc: |
      タイトル部分に表示する文字列
    type: 'string'
    default: 'ニコニ広告'
  baseMessage:
    parent: 'base'
    name: 'メッセージ'
    desc: |
      メッセージの最後につける感謝の言葉
    type: 'string'
    default: '広告ありがとうございます！'
  baseBackgroundColor:
    parent: 'base'
    name: '背景色'
    desc: |
      背景の色
      （※CSSと同様の指定方法です）
    type: 'string'
    default: 'rgba(255, 229, 0, .8)'
  baseTextColor:
    parent: 'base'
    name: '文字色'
    desc: |
      文字の色
      （※CSSと同様の指定方法です）
    type: 'string'
    default: '#000000'
  baseScrollTime:
    parent: 'base'
    name: '表示時間'
    desc: |
      文字が流れきるのにかかる時間（秒）
    type: 'number'
    default: 10
  advanced:
    dummy: '■ 上級者設定'
  advancedAutoStart:
    parent: 'advanced'
    name: '自動開始'
    desc: |
      ゲーム開始と同時に表示を始めるか？
    type: 'boolean'
    ON: 始める
    OFF: 始めない
    default: true
  advancedExpiration:
    parent: 'advanced'
    name: '対象時間'
    desc: |
      何秒前の広告までを対象にするか？
    type: 'number'
    default: 604800
  advancedFetchInterval:
    parent: 'advanced'
    name: '自動取得間隔'
    desc: |
      ニコニ広告情報の自動取得の間隔（分）
      0の場合は再取得しません
    type: 'number'
    default: 5

Torigoya_NiconikoBar:
  <<: *base
  target: 'MV'
  parameter:
    <<: *parameterBase

TorigoyaMZ_NiconikoBar:
  <<: *base
  target: 'MZ'
  parameter:
    <<: *parameterBase
  commands:
    start:
      name: 'ニコニ広告情報の取得開始'
      desc: |
        ニコニ広告情報の取得を開始します。
        取得した場合自動的にバーを表示します。
    stop:
      name: 'ニコニ広告情報の取得停止'
      desc: |
        ニコニ広告情報の取得を停止します。
        停止中はバーが表示されません。
