base: &base
  version: '1.3.0'
  title:
    ja: 'アイテム上限数個別指定プラグイン'
  body:
    ja: |
      アイテムの所持できる上限を
      メモ欄で個別に設定できるようにします。

      ------------------------------------------------------------
      ■ メモの指定方法
      ------------------------------------------------------------

      各アイテムのメモ欄に指定してください。

      ▼ 例1）上限を15個にする

      <MaxItems: 15>

      または

      <最大所持数: 15>

      ▼ 例2）上限を【変数1】で指定した数にする

      <MaxItems: v[1]>

      または

      <最大所持数: v[1]>
  parameter: {}

Torigoya_MaxItems:
  <<: *base
  target: 'MV'

TorigoyaMZ_MaxItems:
  <<: *base
  target: 'MZ'
  commands:
    adjustItems:
      name: 'アイテム所持数の調整'
      desc: |
        最大所持数を超えたアイテムがある場合に
        上限を超えないようにアイテムを自動で減らします
