base: &base
  version: '1.0.1'
  title:
    ja: '変数ラベルジャンププラグイン'
  parameter: {}

Torigoya_JumpVariableLabel:
  <<: *base
  target: 'MV'
  body:
    ja: |
      イベントコマンドの「ラベルジャンプ」で変数を使用できるようにします。

      ------------------------------------------------------------
      ■ 使用方法
      ------------------------------------------------------------
      このプラグインを導入すると、
      「ラベルジャンプ」で指定するテキスト内に
      以下の記法が利用できるようになります。

      \V[変数ID]

      ※「文章の表示」で使用できる変数の指定と同じ、Vは小文字でもOKです

      ▼ 例：「状態_変数の中身」のようなラベルにジャンプしたい場合
      状態_\v[1]

TorigoyaMZ_JumpVariableLabel:
  <<: *base
  target: 'MZ'
  body:
    ja: |
      イベントコマンドの「ラベルジャンプ」で変数を使用できるようにします。

      ------------------------------------------------------------
      ■ 使用方法
      ------------------------------------------------------------
      このプラグインを導入すると、
      「ラベルジャンプ」で指定するテキスト内に
      以下の記法が利用できるようになります。

      \V[変数ID]

      ※「文章の表示」で使用できる変数の指定と同じ、Vは小文字でもOKです

      ▼ 例：「状態_変数の中身」のようなラベルにジャンプしたい場合
      状態_\v[1]

      ------------------------------------------------------------
      ■ オプション機能：PluginCommonBase連携
      ------------------------------------------------------------
      公式プラグインの「PluginCommonBase」や
      「TextScriptBase」が入っている場合、
      それぞれの対応する記法も使用できるようになります。

      ▼ PluginCommonBase
      \s[スイッチID]
      \ss[セルフスイッチID]

      ▼ TextScriptBase
      \tx[登録テキストの識別子]
      \js[登録スクリプトの識別子]
      \js<スクリプト>

      各記法の詳細は、それぞれのプラグインの説明をご確認ください。
  orderAfter:
    - 'PluginCommonBase'
    - 'TextScriptBase'
