base: &base
  version: '1.0.0'
  title:
    ja: 'カスタムターン回復＆ダメージ設定プラグイン'
  body:
    ja: |
      毒などのターン毎の回復・ダメージ量をメモ欄で設定できるようにします。
      毎ターン固定10ダメージ、のようなものを作りやすくします。

      ------------------------------------------------------------
      ■ 設定方法
      ------------------------------------------------------------
      ステート等のメモ欄に以下のように設定してください。

      ■ 例1：毎ターンHPを10回復

      <CustomRegenerateHP: 10>

      ■ 例2：毎ターンMPに20ダメージ

      <CustomRegenerateMP: -20>

      ※マイナスにすると回復になります

      ■ 例3（プロ向け）：毎ターン現在HPの10%ダメージ

      <CustomRegenerateHP: -0.1 * a.hp>

      ※ダメージ計算のように「a」に自分自身が入ります。
      　ただしダメージ計算と違って「b」はないので気をつけてね！
  parameter:
    advanced:
      dummy: '■ 上級者設定'
    advancedNoteTagHp:
      parent: 'base'
      name: 'HP用のメモタグ'
      desc: |
        メモ欄に指定するタグの名前（HP用）
        空欄の場合は機能が無効になります
      type: 'string'
      default: 'CustomRegenerateHP'
    advancedNoteTagMp:
      parent: 'base'
      name: 'HP用のメモタグ'
      desc: |
        メモ欄に指定するタグの名前（MP用）
        空欄の場合は機能が無効になります
      type: 'string'
      default: 'CustomRegenerateMP'
    advancedNoteTagTp:
      parent: 'base'
      name: 'HP用のメモタグ'
      desc: |
        メモ欄に指定するタグの名前（TP用）
        空欄の場合は機能が無効になります
      type: 'string'
      default: 'CustomRegenerateTP'

Torigoya_CustomRegenerate:
  <<: *base
  target: 'MV'

TorigoyaMZ_CustomRegenerate:
  <<: *base
  target: 'MZ'
