parameterBase: &parameterBase
  base:
    dummy: '■ 基本設定'
  baseAchievementData:
    parent: 'base'
    name: '実績情報の登録'
    type: 'Achievement'
    array: true
    default: []
  baseSaveSlot:
    parent: 'base'
    name: 'セーブデータのスロット名'
    default: ''
  popup:
    dummy: '■ ポップアップ設定'
  popupEnable:
    parent: 'popup'
    name: 'ポップアップ表示のON/OFF'
    desc: |
      実績を獲得した時にポップアップ表示を行うか？
    type: 'boolean'
    on: '表示する'
    off: '表示しない'
    default: true
  popupPosition:
    parent: 'popup'
    name: '表示位置'
    desc: |
      実績獲得ポップアップが表示される位置
    type: 'select'
    option:
      - name: '左上'
        value: 'leftUp'
      - name: '右上'
        value: 'rightUp'
    default: 'leftUp'
  popupAnimationType:
    parent: 'popup'
    name: 'アニメーション'
    desc: |
      実績獲得ポップアップのアニメーション方法
      「なめらか」はTorigoya_FrameTween.jsが必要です
    type: 'select'
    option:
      - name: 'なめらか'
        value: 'tween'
      - name: 'その場に表示'
        value: 'open'
    default: 'tween'
  popupWait:
    parent: 'popup'
    name: '表示時間'
    desc: |
      実績獲得ポップアップの表示時間（秒）
      ※アニメーションの時間は含みません
    type: 'number'
    decimals: 2
    min: 0
    default: 1.25
  popupWidth:
    parent: 'popup'
    name: 'ポップアップの横幅'
    desc: |
      実績獲得ポップアップの横幅（px）
      小さすぎると文字がはみ出します
    type: 'number'
    min: 200
    default: 300
  popupPadding:
    parent: 'popup'
    name: 'ポップアップの余白'
    desc: |
      実績獲得ポップアップの余白サイズ
    type: 'number'
    min: 0
    default: 10
  popupTitleFontSize:
    parent: 'popup'
    name: '実績名の文字サイズ'
    desc: |
      実績獲得ポップアップに表示される
      取得した実績名の文字サイズ
    type: 'number'
    min: 16
    default: 20
  popupTitleColor:
    parent: 'popup'
    name: '実績名の文字の色番号'
    desc: |
      実績名の文字表示に使用する色
      ※\c[数字] ←の数字欄に入れる数字
    type: 'number'
    min: 0
    default: 1
  popupMessage:
    parent: 'popup'
    name: 'メッセージの内容'
    desc: |
      実績獲得ポップアップに表示される
      獲得メッセージの内容
    default: '実績を獲得しました'
  popupMessageFontSize:
    parent: 'popup'
    name: 'メッセージの文字サイズ'
    desc: |
      実績獲得ポップアップに表示される
      獲得メッセージの文字サイズ
    type: 'number'
    min: 12
    default: 16
  popupSound:
    parent: 'popup'
    type: 'Sound'
    name: '効果音'
    desc: |
      実績獲得時に再生する効果音の設定
    default: '{"soundName":"Saint5","soundVolume":"90"}'
  popupWindowImage:
    parent: 'popup'
    name: 'ウィンドウ画像'
    desc: |
      実績獲得ポップアップのウィンドウ画像
    type: 'file'
    dir: 'img/system/'
    default: 'Window'
  popupOpacity:
    parent: 'popup'
    name: 'ウィンドウ背景の透明度'
    desc: |
      ウィンドウ背景の透明度(0～255)
      -1の場合はデフォルトの透明度を使用します
    type: 'number'
    min: -1
    max: 255
    default: -1
  titleMenu:
    dummy: '■ タイトル / メニュー画面設定'
  titleMenuUseInTitle:
    parent: 'titleMenu'
    name: 'タイトル画面に表示'
    desc: |
      タイトル画面に実績メニューを表示するか？
    type: 'boolean'
    on: '表示する'
    off: '表示しない'
    default: true
  titleMenuUseInMenu:
    parent: 'titleMenu'
    name: 'メニュー画面に表示'
    desc: |
      メニュー画面に実績メニューを表示するか？
    type: 'boolean'
    on: '表示する'
    off: '表示しない'
    default: true
  titleMenuText:
    parent: 'title'
    name: '項目名'
    desc: |
      タイトルやメニューに表示する際の
      実績メニューの項目名
    default: '実績'
  achievementMenu:
    dummy: '■ 実績画面設定'
  achievementMenuHiddenTitle:
    parent: 'achievementMenu'
    name: '未獲得実績の表示名'
    desc: |
      実績画面で未取得の実績の欄に
      表示する名前
    default: '？？？？？'
  achievementMenuHiddenIcon:
    parent: 'achievementMenu'
    name: '未獲得実績のアイコンID'
    desc: |
      実績画面で未取得の実績の欄に
      表示するアイコンのID
    type: 'number'
    default: 0
  advanced:
    dummy: '■ 上級者向け設定'
  advancedOverwritable:
    parent: 'advanced'
    name: '獲得済み実績の再取得'
    desc: |
      既に獲得済みの実績でも再取得できるようにします
    type: 'boolean'
    on: 'する'
    off: 'しない'
    default: false

structureBase: &structureBase
  Sound:
    soundName:
      name: '効果音ファイル名'
      desc: |
        実績獲得ポップアップ表示時に再生する効果音ファイル
        空っぽの場合は効果音なしになります
      type: 'file'
      dir: 'audio/se/'
      default: 'Saint5'
    soundVolume:
      name: '効果音の音量'
      desc: |
        実績獲得ポップアップ表示時に再生する効果音の音量
      type: 'number'
      min: 0
      max: 100
      default: 90
  Achievement:
    key:
      name: '管理ID'
      desc: |
        実績獲得時に指定する名前（例: ゲームクリア）
        数字でも日本語でもOK / 他の実績と被るのはNG
      type: 'string'
    title:
      name: '表示名'
      desc: |
        実績に画面に表示するときの実績名
        （例：激闘の果てに魔王を倒した…ッ！）
      default: ''
    description:
      name: '実績の説明文'
      desc: |
        実績に画面に表示する説明文（2行程度）
      type: 'multiline_string'
      default: ''
    icon:
      name: '実績のアイコンID'
      type: 'number'
      default: 0
    hint:
      name: '実績獲得のヒント'
      desc: |
        未取得の場合に取得方法を表示できます（2行程度）
        空欄の場合は通常の説明文を表示します
      type: 'multiline_string'
      default: ''
    isSecret:
      name: '秘密実績フラグ'
      desc: |
        この実績の存在を秘密にします
        未獲得の場合に一覧に表示されなくなります
      type: 'boolean'
      on: '秘密にする'
      off: '秘密にしない'
      default: false

base: &base
  version: '1.0.1'
  title:
    ja: '実績プラグイン'
  body:
    ja: |
      実績・トロフィー的なシステムを定義します。
      使用方法の詳細は以下の記事をご確認ください。
      https://torigoya-plugin.rutan.dev/system/achievement2/
  parameter:
    <<: *parameterBase
  structures:
    <<: *structureBase

Torigoya_Achievement2:
  <<: *base
  target: 'MV'
  parameter:
    <<: *parameterBase
    achievementMenuCancelMessage:
      parent: 'achievementMenu'
      name: '閉じるボタンのテキスト'
      desc: |
        実績画面を閉じるボタンのテキスト
        空欄の場合は閉じるボタンを表示しません
      default: '閉じる'

TorigoyaMZ_Achievement2:
  <<: *base
  target: 'MZ'
  commands:
    gainAchievement:
      name: '実績の獲得'
      desc: '指定した実績を獲得します'
      parameter:
        key:
          type: 'string'
          name: '実績の管理ID'
          desc: '獲得したい実績に設定したIDを指定'
    removeAchievement:
      name: '獲得済み実績の削除'
      desc: |
        既に獲得済みの実績を未獲得状態にします。
        未獲得だった場合は何もしません。
      parameter:
        key:
          type: 'string'
          name: '実績の管理ID'
          desc: '削除したい実績に設定したIDを指定'
    openSceneAchievement:
      name: '実績画面の表示'
      desc: |
        獲得済み実績の一覧画面を表示します。
    resetAchievement:
      name: '全実績の削除（注意！）'
      desc: |
        すべての実績を獲得前の状態に戻します。
        気をつけて使おう！

addonTileViewBase: &addonTileViewBase
  version: '0.0.0'
  title:
    ja: '実績プラグインアドオン: タイル表示'
  body:
    ja: |
      このプラグインは「実績プラグイン」のアドオンです。
      実績プラグインより下に導入してください。

      獲得した実績の一覧画面をテキストではなく
      アイコンで表示するように変更します
  parameter:
    base:
      dummy: '■ 基本設定'
    colsSize:
      parent: 'base'
      name: '表示数（横）'
      type: 'number'
      min: 1
      desc: |
        一列に表示するアイコンの個数
      default: 5
    itemPadding:
      parent: 'base'
      name: 'アイコンの余白'
      type: 'number'
      min: 0
      desc: |
        アイコンの周囲の余白(px)
      default: 5

Torigoya_Achievement2_AddonTileView:
  <<: *addonTileViewBase
  target: 'MV'

TorigoyaMZ_Achievement2_AddonTileView:
  <<: *addonTileViewBase
  target: 'MZ'
  base:
    - 'TorigoyaMZ_Achievement2'
  orderAfter:
    - 'TorigoyaMZ_Achievement2'
