base: &base
  version: '1.0.0'
  title:
    ja: '同じ名前の装備タイプなら同じものを装備できるようにするプラグイン'
  body:
    ja: |
      データベースの「タイプ」→「装備タイプ」設定で
      同じ名前を設定した場合は、同じ種別のアイテムを装備できるようにします。

      例えば

      01 武器
      02 盾
      03 装飾品
      04 装飾品
      05 装飾品

      のように設定した場合、装備の3段目〜5段目がすべて
      「03 装飾品」が装備できるスロットになります。

      ※装備の設定をする際は必ず同じ名前でも
      　一番上にあるものにしてください。
      　上記の例の場合であれば装飾品はすべて「03 装飾品」になります。
  parameter: []

Torigoya_SameEquipType:
  <<: *base
