base: &base
  version: '1.1.0'
  title:
    ja: 'テキスト本棚プラグイン'
  body:
    ja: |
      テキストファイルから本棚シーンを作成します。
      使い方の詳細は解説ページをご覧ください。
      https://torigoya-plugin.rutan.dev/system/bookshelf/

      ------------------------------------------------------------
      ■ 基本的な使い方
      ------------------------------------------------------------
      (1) 本棚テキストを置くフォルダをつくる

      プロジェクトのフォルダ（img などの横）に、
      bookshelf
      という名前のフォルダを作成してください。

      (2) 本棚用のテキストファイルを作成する

      後述の形式のテキストファイルを bookshelf フォルダ内に作成してください。
      テキストはいくつでも設置できます。

      (3) プラグインコマンドで呼び出す

      本棚を呼び出したいイベントから
      プラグインコマンドで表示したいテキストファイルを指定します。

      ■ MZの場合
      プラグインコマンドから「本棚の表示」を選んでください
      パラメータ欄にテキストファイルの名前を指定します

      ■ MVの場合
      プラグインコマンドに以下のように記述してください

      本棚表示 xxxxx

      xxxxx の部分は読み込みたいテキストファイルの名前にしてください

      ------------------------------------------------------------
      ■ テキストの書き方
      ------------------------------------------------------------
      ※見づらいので、解説ページを見ることをオススメします＞＜

      テキストファイル内で本棚のタイトルを指定できます。
      以下のように、シャープ1個を先頭につけ、その後ろにタイトルを記述してください。

      # ここに本棚のタイトル

      なお、タイトルが未設定の場合は、
      本棚画面でタイトル欄が非表示になります。


      ■ 本棚の中に本を追加する
      以下のように、シャープ2個を先頭につけた行が本のタイトルになり、
      その次の行からが本の中身になります。
      本の中身には、「文章の表示」同様に \c[2] などのコマンドが使えます。

      ## 1冊目の本のタイトル
      ここに本文
      ここに本文

      ## 2冊目の本のタイトル
      ここに本文
      文章の表示同様に\c[2]文字の色を変えたり\c[0]できます


      ■ 本のページを増やす
      このプラグインは文章がはみ出しても
      自動的にページを切り替えたりはしません。
      手動でページ切り替えを記述する必要があります。
      ページ切り替えをしたい場所で、
      以下のようにハイフンを3個以上並べてください。

      ## 本のタイトル
      1ページ目の本文

      ----------

      2ページ目の本文


      ■ 本文の中に画像を表示する
      本文の中に以下のように記述することで、
      文章の間に顔グラやピクチャーを表示できます。

      \bookFace 顔グラ画像の名前, 番号

      \bookPicture ピクチャーの名前

parameterBase: &parameterBase
  base:
    dummy: '■ 基本設定'
  bookshelfTitleFontSize:
    parent: 'base'
    name: '本棚名の文字サイズ'
    type: 'integer'
    desc: |
      本棚の名前のフォントサイズを指定します
    min: 1
    default: 22
  bookshelfWidth:
    parent: 'base'
    name: '本の一覧の横幅'
    type: 'integer'
    desc: |
      本棚画面の本の一覧の横幅を指定します
      0の場合、UI領域をすべて使用します。
    min: 0
    default: 400
  bookshelfMaxHeight:
    parent: 'base'
    name: '本の一覧の最大縦幅'
    type: 'integer'
    desc: |
      本棚画面の本の一覧の最大縦幅を指定します。
      0の場合、UI領域をすべて使用します。
    min: 0
    default: 0
  bookContentFontSize:
    parent: 'base'
    name: '本の中身の文字サイズ'
    type: 'integer'
    desc: |
      本の中身ウィンドウのフォントサイズを指定します。
    min: 1
    default: 24
  bookContentWidth:
    parent: 'base'
    name: '本の中身の横幅'
    type: 'integer'
    desc: |
      本の中身ウィンドウの横幅を指定します。
      0の場合、UI領域をすべて使用します。
    min: 0
    default: 0
  bookContentHeight:
    parent: 'base'
    name: '本の中身の縦幅'
    type: 'integer'
    desc: |
      本の中身ウィンドウの縦幅を指定します。
      0の場合、UI領域をすべて使用します。
    min: 0
    default: 0
  menu:
    dummy: '■ メニュー設定'
  menuItems:
    parent: 'menu'
    name: 'メニューに本棚を追加'
    type: 'MenuItem'
    array: true
    default: []

structureBase: &structureBase
  MenuItem:
    name:
      name: '項目名'
      type: 'string'
      desc: |
        メニューに表示される項目の名前
      default: ''
    fileName:
      name: '本棚のファイル名'
      type: 'string'
      desc: |
        読み込むテキストのファイル名を指定してください
        フォルダ(bookshelf)の名前は含める必要ありません
      default: ''
    switchId:
      name: '有効スイッチ'
      desc: |
        このスイッチがONのときのみ選択できるようにします
        なしの場合は、常に選択できます
      type: 'switch'
      default: 0
    visibility:
      name: '無効時に表示するか'
      desc: |
        有効スイッチがONじゃないときに
        項目をメニューに表示するか設定できます
      type: 'boolean'
      on: '表示する'
      off: '表示しない'
      default: 'true'
    note:
      name: 'メモ'
      desc: |
        メモ欄です。
        ツクールのメモ欄同様に使えます。
      type: 'multiline_string'
      default: ''

Torigoya_Bookshelf:
  <<: *base
  target: 'MV'
  parameter:
    <<: *parameterBase
  structures:
    <<: *structureBase

TorigoyaMZ_Bookshelf:
  <<: *base
  target: 'MZ'
  parameter:
    <<: *parameterBase
  structures:
    <<: *structureBase
  commands:
    openBookshelf:
      name: '本棚の表示'
      desc: '指定ファイルを読み込み、本棚を表示します'
      parameter:
        fileName:
          type: 'text'
          name: 'ファイル名'
          desc: |
            読み込むテキストのファイル名を指定してください
            フォルダ(bookshelf)の名前は含める必要ありません
