name: update github pages
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-22.04
    env:
      TZ: 'Asia/Tokyo'
    steps:
      - uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: public

      - uses: actions/checkout@v3
        with:
          ref: main
          path: main

      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'yarn'
          cache-dependency-path: main/yarn.lock

      - run: yarn install --frozen-lockfile
        working-directory: ./main

      - run: yarn build
        working-directory: ./main

      - run: node ./scripts/copy-to-public.js ../public
        working-directory: ./main

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          allow_empty_commit: true
