name: update github pages
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-22.04
    env:
      TZ: 'Asia/Tokyo'
    steps:
      - uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: public

      - uses: actions/checkout@v4
        with:
          ref: main
          path: main

      - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v.4.0.0
        with:
          run_install: false
          package_json_file: 'main/package.json'

      - uses: actions/setup-node@v4
        with:
          node-version-file: 'main/package.json'
          cache: 'pnpm'
          cache-dependency-path: 'main/pnpm-lock.yaml'

      - run: pnpm install
        working-directory: ./main

      - run: pnpm run build
        working-directory: ./main

      - run: node ./scripts/copy-to-public.js ../public
        working-directory: ./main

      - name: Deploy
        uses: peaceiris/actions-gh-pages@373f7f263a76c20808c831209c920827a82a2847 # v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
