name: update github pages
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      TZ: 'Asia/Tokyo'
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v.6.0.1
        with:
          ref: gh-pages
          path: public

      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v.6.0.1
        with:
          ref: main
          path: main

      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v.4.2.0
        with:
          run_install: false
          package_json_file: 'main/package.json'

      - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v.6.1.0
        with:
          node-version-file: 'main/.node-version'
          cache: 'pnpm'
          cache-dependency-path: 'main/pnpm-lock.yaml'

      - run: pnpm install
        working-directory: ./main

      - run: pnpm run build
        working-directory: ./main

      - run: node ./scripts/copy-to-public.js ../public
        working-directory: ./main

      - name: Deploy
        uses: peaceiris/actions-gh-pages@373f7f263a76c20808c831209c920827a82a2847 # v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
